string_input = input("Enter a string: ")
integer_input = int(input("Enter an integer: "))
float_input = float(input("Enter a float: "))
print("String : ",string_input )
print("Integer : ",integer_input )
print("float",float_input)